### ISSUE TITLE
Switching between dropdown menus causes application crash

### ISSUE THREAD

**Issue by procedural** [vurtun/zahnrad#13]
I can't get backtrace out of GDB, it hangs when this crash happens, but it's easily reproducible:

<img src="http://i.imgur.com/XX42tGv.gif"/>

Click on `FILE` (gif didn't captured drop down menu, bit it was there) then on `EDIT` menu.

**Comment by vurtun** [comment]
Thanks for your feedback. I am currently right at this moment working on the menu to enable deeper menu levels. So I will finish the menu code first and see if it still persists and if so fix it.

**Comment by vurtun** [comment]
I uploaded the fix for the menu and directly found another bug and fixed that bug as well. It should hopefully work now.

**Comment by procedural** [comment]
Yep, it works now! Thank you, @vurtun!
