### ISSUE TITLE
Sample code issues v2

### ISSUE THREAD

**Issue by ktb92677** [vurtun/zahnrad#15]
Hey! Just wanted to list here some issues with your sample code:

"zr_combo(&context, items, LEN(items), &item, 20, &active);"
zr_combo isn't a function.

"zr_window_init(&window, 50, 50, 220, 180,
    ZR_WINDOW_BORDER|ZR_WINDOW_MOVEABLE|ZR_WINDOW_SCALEABLE,
    &queue, &style, &input);"

This function actually requires a "zr_rect"

Just wanted to mention these! Thanks for all your hard work here.

**Comment by vurtun** [comment]
Hey, thanks for always finding and posting issues. It is really hard to check everything with all these refactoring changes so it is always nice to have people find and mention problems. As for issue #14 and #15 they are hopefully fixed now.
