### ISSUE TITLE
Issues with graphics disappearing

### ISSUE THREAD

**Issue by ktb92677** [vurtun/zahnrad#16]
Hey, I have the following code currently running:

<pre>
#include "Utilities/Themis.h"

#define MEMORY_SIZE  (64 * 1024)

using namespace std;

Themis *main_controller;

zr_style style;
zr_user_font font;
zr_command_queue queue;
zr_window window;

enum {EASY, HARD};
zr_size option;
zr_float value;
struct zr_input input;

MouseInfo temp;

static zr_size font_get_text_width(zr_handle handle, const zr_char *t, zr_size l) {
    return main_controller->graphics_handle->getStringLength(t, l);
}

int main(int argc, char **argv) {
	main_controller = new Themis();
	main_controller->Init(argc, argv); //initializes everything for you
	//Frame frame(main_controller, 50, 50, 220, 180);
	
	font.userdata.ptr = this;
	font.height = 10;
	font.width = font_get_text_width;
	zr_style_default(&style, ZR_DEFAULT_ALL, &font);

	/* allocate memory to hold draw commands */
	zr_command_queue_init_fixed(&queue, malloc(MEMORY_SIZE), MEMORY_SIZE);

	/* initialize window */
	zr_window_init(&window, zr_rect(50, 50, 220, 180),
	ZR_WINDOW_BORDER,
	&queue, &style, &input);

	/* setup widget data */
	option = EASY;
	value = 0.6f;
	
	temp.x.data = 0;
	temp.y.data = 0;
	
	while (true) {
		//frame.handle_input();
		
		zr_input_begin(&input);
		// record input

		/*
		if (main_controller->mouseInfo.button.data == 0) {
				zr_input_button(&input, ZR_BUTTON_LEFT, main_controller->mouseInfo.x.data, main_controller->mouseInfo.y.data, zr_true);
		} else {
				zr_input_button(&input, ZR_BUTTON_LEFT, main_controller->mouseInfo.x.data, main_controller->mouseInfo.y.data, zr_false);
		}
		if (main_controller->mouseInfo.x.data != temp.x.data || main_controller->mouseInfo.y.data != temp.y.data) {
				zr_input_motion(&input, temp.x.data, temp.y.data);
				temp.x.data = main_controller->mouseInfo.x.data;
				temp.y.data = main_controller->mouseInfo.y.data;
		}

		if (main_controller->keyboardInfo.c != 0 && main_controller->keyboardInfo.state.data != 0)
				zr_input_char(&input, main_controller->keyboardInfo.c);
		else if (main_controller->keyboardInfo.code.data == 14)
				if (main_controller->keyboardInfo.state.data != 0)
						zr_input_key(&input, ZR_KEY_BACKSPACE, zr_true);
				else
						zr_input_key(&input, ZR_KEY_BACKSPACE, zr_false);
		*/
		zr_input_end(&input);
		
		//frame.construct();
		
		zr_context context;
		zr_begin(&context, &window);
		const char *items[] = {"Fist", "Pistol", "Railgun", "BFG"};
		zr_header(&context, "Show", 0, 0, ZR_HEADER_LEFT);
		/*
		zr_layout_row_static(&context, 30, 80, 1);
		if (zr_button_text(&context, "button", ZR_BUTTON_DEFAULT)) {
			// event handling
		}
		zr_layout_row_dynamic(&context, 30, 2);
		if (zr_option(&context, "easy", option == EASY)) option = EASY;
		if (zr_option(&context, "hard", option == HARD)) option = HARD;
		zr_layout_row_begin(&context, ZR_STATIC, 30, 2);
		{
			zr_layout_row_push(&context, 50);
			zr_label(&context, "Volume:", ZR_TEXT_LEFT);
			zr_layout_row_push(&context, 110);
			value = zr_slider(&context, 0, value, 1.0f, 0.1f);
		}
		zr_layout_row_end(&context);
		*/
		zr_end(&context, &window);
		
		//frame.draw();
		
		while (!main_controller->render) {}
		main_controller->graphics_handle->SetPriority(0); //just a formality, doesn't do anything considering the entire array is filled with -1
		fill_n(main_controller->graphics_handle->buffer_i, main_controller->screen_width.data * main_controller->screen_height.data, -1);
		const struct zr_command *cmd;
		Integer colorC;
		main_controller->graphics_handle->SetPriority(2);
		zr_foreach_command(cmd, &queue) {
			switch (cmd->type) {
				case ZR_COMMAND_SCISSOR: {
				const struct zr_command_scissor *s = zr_command(scissor, cmd);
				main_controller->graphics_handle->setClip(s->x, s->y, s->w, s->h);
				break;
				}
				case ZR_COMMAND_LINE: {
				const struct zr_command_line *l = zr_command(line, cmd);
				colorC.bytes[3] = 2; // setting priority
				colorC.bytes[0] = l->color.r;
				colorC.bytes[1] = l->color.g;
				colorC.bytes[2] = l->color.b;
				main_controller->graphics_handle->drawLine(l->begin.x, l->begin.y, l->end.x, l->end.y, colorC.data);
				break;
				}
				case ZR_COMMAND_RECT: {
				const struct zr_command_rect *r = zr_command(rect, cmd);
				colorC.bytes[3] = 2; // setting priority
				colorC.bytes[0] = r->color.r;
				colorC.bytes[1] = r->color.g;
				colorC.bytes[2] = r->color.b;
				main_controller->graphics_handle->fillSquare(r->x, r->y, r->w, r->h, colorC.data);
				break;
				}
				case ZR_COMMAND_CIRCLE: {
				const struct zr_command_circle *c = zr_command(circle, cmd);
				colorC.bytes[3] = 2; // setting priority
				colorC.bytes[0] = c->color.r;
				colorC.bytes[1] = c->color.g;
				colorC.bytes[2] = c->color.b;
				main_controller->graphics_handle->fillCircle(c->x + (c->w / 2), c->y + (c->w / 2), c->w / 2, colorC.data);
				break;
				}
				case ZR_COMMAND_TRIANGLE: {
				const struct zr_command_triangle *t = zr_command(triangle, cmd);
				colorC.bytes[3] = 2; // setting priority
				colorC.bytes[0] = t->color.r;
				colorC.bytes[1] = t->color.g;
				colorC.bytes[2] = t->color.b;
				Polygon tri;
				tri.addPoint(t->a.x, t->a.y);
				tri.addPoint(t->b.x, t->b.y);
				tri.addPoint(t->c.x, t->c.y);
				main_controller->graphics_handle->fillPolygon(tri, colorC.data);
				break;
				}
				case ZR_COMMAND_TEXT: {
				const struct zr_command_text *t = zr_command(text, cmd);
				main_controller->graphics_handle->drawString(t->string, t->x, t->y + 10, _WHITE);
				break;
				}
			}
		}
		main_controller->graphics_handle->setClip(-1, -1, -1, -1);
		main_controller->render = false;
		
		cout << "drew" << endl;
	}
	return 0;
}
</pre>

Please make a note that most of the code is commented out. I have been looking through all of my code and I can't find anything wrong with it. Anyways the error here is that the window shows up for a very temporary time and then disappears. However the program itself does not crash. It's almost as if the algorithm just stops generating squares and such to generate. If you get a chance could you please take a look? I originally thought maybe the window was closing but closing is set to 0 in the header and input isn't even being processed. Thanks!

**Comment by vurtun** [comment]
Hey, stupid question but did you clear the command queue after drawing each command?

**Comment by ktb92677** [comment]
*face palm* Jeez, sorry about wasting your time here.

An interesting idea might be to implement some sort of error catching functionality or something. Like a quick printf if I've run out of space on the queue. But this is a silly mistake so maybe it's not necessary

**Comment by vurtun** [comment]
No problem I had the same problem today while updating the old win32 demo, so even I made the same mistake. About the error message what I could do is add a assert to check if no more memory is left. If that would not sufficient enough I would have to think about logging.

**Comment by ktb92677** [comment]
No no an assert would do just fine! At least then the program crashes which will lead me to think segfault which will lead me to think array index out of bounds etc. Though logging would be nice too :)
