### ISSUE TITLE
win32 demo compilation problems

### ISSUE THREAD

**Issue by radishdalek** [vurtun/zahnrad#23]
I ran the "make.bat" file (in the win32 demo section) using the "Developer Command Prompt for VS2015" using administrator privileges, but encountered two errors in the win32.c

win32.c(404): error C2065: 'zr_float': undeclared identifier
win32.c(404): error C2146: syntax error: missing ';' before identifier 'xw'

It fails to create the executable in the bin folder

[Visual studio 2015, Windows 10]

**Comment by vurtun** [comment]
Hey,
thanks for your feedback. I forgot to update the win32 example, but it should now be fixed.
