### ISSUE TITLE
Minor: spelling mistakes in API

### ISSUE THREAD

**Issue by dumblob** [vurtun/zahnrad#27]
Please don't consider this as nitpicking. I would just like Zahnrad to be the best imgui written in C with stable API.

Except for few spelling mistakes in the documentation (which is not a big deal - I want to issue a pull request during the next 7 days and as I'm not a native speaker, I'll definitely unintentionally skip some typos), I'm more concerned about ones in the API - e.g. functions containing `glyphes` should rather contain `glyphs` (some internal structures and variables contain this typo as well). In addition, today I found `modifyable` -> `modifiable`.

**Comment by vurtun** [comment]
Hey,
> I would just like Zahnrad to be the best imgui written in C with stable API.

Thanks nice to hear that.

> Except for few spelling mistakes in the documentation (which is not a big deal - I want to issue a 
 pull request during the next 7 days and as I'm not a native speaker, I'll definitely unintentionally
 skip some typos)

You are more than welcome to provide a PR, not only for spelling mistakes. I often do not notice them but they create a bad image of this library so it is great to have someone at least notice them.

> I'm more concerned about ones in the API - e.g. functions containing glyphes should rather contain glyphs (some internal structures and variables contain this typo as well). In addition, today I found modifyable -> modifiable.

Thanks I pushed a commit fixing bot spelling mistakes.
