### ISSUE TITLE
Enhancement: avoid static on non-const variables

### ISSUE THREAD

**Issue by dumblob** [vurtun/zahnrad#29]
Probably the last code-related thing I'm concerned with is the use of Zahnrad in multi-threaded applications, because some functions still contain non-const variables which are static (`zr_draw_list_path_arc_to_fast()`, `zr_font_japanese_glyph_range()`, `zr_style_property()`, `
zr_style_color()`). It would be better to add them to some external state structure and/or to API.

**Comment by vurtun** [comment]
`zr_draw_list_path_arc_to_fast` and `zr_font_japanese_glyph_range` could probably be solved by providing a way to initialize the data before accessing them to solve the issue. `zr_style_property` and  `zr_style_color` just need to be converted to const since I only use them for a zero instance of type `struct zr_vec`. I will fix and push the const issue immediately and look into fixing the other two as well.

**Comment by vurtun** [comment]
`zr_style_property` and ´zr_style_color´ should now be fixed. For `zr_draw_list_path_arc_to_fast` I wrote a special Initializer function `zu_draw_list_setup` and for `zr_font_japanese_glyph_range` I just added a comment to point out that you have to call this once before using multithreaded.

**Comment by dumblob** [comment]
>I just added a comment to point out that you have to call this once before using it in a multithreaded context.

From my experience this is not enough. E.g. if zahnrad were a module for Python/Ruby/whatever (which is quite likely), such module could be loaded from different places of a bigger program in different threads and the issue will remain.

**Comment by dumblob** [comment]
Well, one more thing, the icing on the cake - add a note about thread-safety to the **Features** section in README.md ;)

**Comment by vurtun** [comment]
Pedantically that wouldn't be true since instances of `zr_context`, `zr_window`, `zr_style`, `zr_command_queue` and `zr_input` can have race conditions if accessed by multiple threads at the same time. It is only thread safe if you access one set of them per thread. Especially the command queue is problematic since it controls the overlapping of windows which complicates threading further.

**Comment by dumblob** [comment]
That's a shame, because modern languages have built-in concurrency support (Go, Rust, Dao, Scala, etc.) and the backends must be obviously thread-safe.

**Comment by dumblob** [comment]
Now after the rewrite, could you please add comments to structures or functions which are not thread-safe to allow wrappers putting locks around them in order to make them thread-safe?

Also, I found `static struct zr_rect null_rect;` declaration in `zr_contextual_begin()` as the only static non-const variable and I wonder why is this one `static`? Also, this variable is not initialized and then its values are read by functions checking the presence of a pointer in the rectangle, which is potentially dangerous as the numbers might widely vary.

**Comment by vurtun** [comment]
I added const to `null_rect` which is not really required since it is a read only variable and does not get modified. As for the state of the variable, it is _always_ guaranteed zero since it is static and just contains four simple float values which definitely fits into the standard.

**Comment by vurtun** [comment]
About Thread safety. GUIs are extremely hard make thread safe. So at them moment there should only be one thread per accessed `zr_context` instance. Each `zr_context` thereby contains his own window stack and therefore the drawing order. So it would only make sense to have multiple `zr_context` instances with each being handled by its own thread if you have multiple UI layers which can be independently drawn (Background, Foreground).

**Comment by dumblob** [comment]
>GUIs are extremely hard make thread safe.

I'm aware of that and that's why I asked for adding precise messages to structures and functions instead of making the code fully thread-safe.

>So it would only make sense to have multiple zr_context instances with each being handled by its own thread if you have multiple UI layers which can be independently drawn (Background, Foreground).

Well, my idea was not vertical scaling (separated layers), but rather horizontal scaling - even low-power devices nowadays have more tiny cores, but need to control big screens with high resolution. That's why I'd like to find a way how to let 4-core low-power CPU be fully utilized - e.g. draw 4 different tiles of the screen in 4 independent threads.

Currently this could be theoretically achieved only if no graphical object would exceed the borders of such tile, but that's such an immense limitation, that it doesn't make sense to even think about it. And I'm not talking about the list of draw commands, but all the computations before as these are preparing the list (even though I didn't do any precise measurements and it's possible, that this won't be a bottleneck for usual interfaces featuring low number of objects in contrast to complex ones like rendering a web page).

On the other hand, if the list of draw commands supported natively division into N (e.g. 4) separated sublists of draw commands for each tile separately, it would be really awesome, because in the end, the user could draw these in parallel e.g. in different threads.

I know, that these paragraphs have not much to do with thread safety, but I just wanted to explain my thoughts (ultimately, there will be a *zahnrad* module for the [Dao programming language](https://github.com/daokoder/dao) which features built-in parallelism).
