### ISSUE TITLE
Minimize / maximize is broken if windows overlap.

### ISSUE THREAD

**Issue by richi** [vurtun/zahnrad#37]
If a minimized window is on top of another one, the maximize button (as well as the close button) won't work. Probably because of:

    if (!(layout->flags & ZR_WINDOW_ROM)) {

In zr_header_button.

If a maximized window is on top of another one and the minimize button is clicked, this window gets send to the background in the next run after releasing the mouse button with zr_input_button.

Cheers, richi

**Comment by vurtun** [comment]
Thanks again,
was a little bit easier than the `ZR_WINDOW_ROM` flag. I just had checks to not set minimized windows on top of the window stack. I removed the checks and it should work now. But I also noticed that if you directly activate a blocked window by clicking it will activate directly on that frame and execute that click on that window. So if you click on X in a non-active window it will activate and then directly close. I don't now if that is right or if it should only by activated on the next frame.
