### ISSUE TITLE
centered text widgets with negative x

### ISSUE THREAD

**Issue by richi** [vurtun/zahnrad#40]
If you move a button (or any other widget with centered text) out of the left side of the screen, x will get negative and the "center" calculation  will give wrong results.

        zr_widget_text, line ~3808

        label.x = (b.x + t->padding.x + ((b.w - 2 * t->padding.x)/2));
        if (label.x >= label.w/2) label.x -= (label.w/2);

replacing those two lines with:

        label.x = (b.x + t->padding.x + ((b.w - 2 * t->padding.x) - label.w) / 2);

might (maybe) solve the problem?

**Comment by vurtun** [comment]
Thanks, so far it seems that everything works fine with the fix.
