### ISSUE TITLE
Sending user data to draw loops

### ISSUE THREAD

**Issue by richi** [vurtun/zahnrad#48]
Imagine you want to control certain aspects of the backend renderer from inside the UI. Right now it is rather difficult to get any kind user data down to the draw loop. 

Would it be possible to append a `zr_handle user_data` to `struct zr_context`, `struct zr_draw_command` and `struct zr_command`. The handling could be similar to `zr_set_font`. 

With `zr_set_user_data(struct zr_context*,zr_handle user_data);` one would set the user data in the context and this data would get passed down to `zr_foreach` or `zr_draw_foreach` through  `struct zr_command ` and `struct zr_draw_command`. 

Until `zr_set_user_data` is called again, always the same user data should end up in the draw loops.

**Comment by vurtun** [comment]
Hey and thanks for the issue,
> Would it be possible to append a zr_handle user_data to struct zr_context, struct zr_draw_command and struct zr_command. The handling could be similar to zr_set_font.

Do you mean same userdata for `zr_context`, `zr_draw_command` and `zr_command` or each having their own? Other than that I don't see a problem of adding it per se but it will blow up the memory consumption for `zr_command` and to some extend in `zr_draw_command` as well. So if I will add userdata to `zr_command` and `zr_draw_command` I will also add defines to make sure not everyone has to pay for the additional costs.

**Comment by richi** [comment]
> or each having their own?

No, no, one for them all would be enough, just like setting a font.

> But can I ask for what this is needed?

Imagine one wants to draw a bunch of buttons each using a different shader:

```` C
for (i = buttonCount; i > 0; i -= 1) {
    zr_set_userdata(context, (zr_handle)shader_for_button(i));
    do_button(i);
    zr_set_userdata(context, (zr_handle)default_shader);
    do_decoration(...);
}
`````

And in the draw loop:

```` C
zr_draw_foreach(cmd, context, &cmds)  {
   shader = (shader_id)cmd->user_data; 
   bind_shader(shader);
   draw_elements(...);
   ...
}
````
> I will also add defines to make sure not everyone

That would be perfect!

**Comment by dumblob** [comment]
I actually think it's worth adding, because tracking the data outside of the draw list would be too cumbersome. So I agree with making it conditional and adding it's use into demos.
