### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ktb92677** [vurtun/zahnrad#51]
Hey! There are some errors when compiling the library right now in c++. Here are the errors:

Frame.cpp:(.text+0x1fc): undefined reference to `zr_label'
/tmp/ccJldMxt.o: In function `zr_tooltip':
zahnrad.c:(.text+0x311c7): undefined reference to `zr_text'
collect2: error: ld returned 1 exit status

Also your demo is off as well, should be zr_panel as opposed to zr_layout.

Thanks!

**Comment by vurtun** [comment]
Hey and thanks for the noticing and report the issue.
The linking error should be fixed now. Was a stupid mistake on my part that does not get caught by C compilers so it took some time to find the problem.
As for the zr_layout I looked into all demos and checked and I could not find a single `struct zr_layout`. Or do you mean the name of each `zr_panel` needs to be changed?

**Comment by ktb92677** [comment]
I was referring to the demo shown on the main screen of the github.

Thanks!
