### ISSUE TITLE
Menu item alignment

### ISSUE THREAD

**Issue by fr500** [vurtun/zahnrad#53]
In most interfaces, menus are left aligned, in zahnrad they are centered and it looks a bit weird.
I added my own method that makes the menu alignment configurable here:
https://github.com/libretro/RetroArch/commit/1b1b59692b208a37833c7021205d87d1d88bc39d

Should I make a pull request or do you have a better idea than duplicating code like this?

**Comment by vurtun** [comment]
Hey,
I did not think anyone would want text alignment in the menu header so I did not add an alignment flag. I looked at your version and I don't think it is worth it to add the same function again. Instead I just added a text alignment flag to `zr_menu_begin_text` which should hopefully suffice.
