### ISSUE TITLE
Clicking items on unfocused windows

### ISSUE THREAD

**Issue by fr500** [vurtun/zahnrad#54]
Clicking an item on a window that is out of focus doesn't produce any result.
While that might be ok, there is no hint that the window is indeed out of focus so it feels a bit odd.

I see two ways to solve this:
- make the items react when click even if the window is not the active window
- make the header a different color for the active window

**Comment by vurtun** [comment]
I debated a lot about this myself and you are probably right. There is even a comment inside `zahnrad.c` in `zr_begin` (`zr_op_begin` in the new version) which allows to uncomment the current behavior and make items react on click even for non-active window. This should hopefully solve the problem and if that does not work I will use a different header color for active windows.

**Comment by fr500** [comment]
Yeah this makes it a lot better in my opinon, the only case where it doesn't work is to drag a window when there is overlap between two windows but that is certainly not a dealbreaker.
