### ISSUE TITLE
zr_window_set_focus not working?

### ISSUE THREAD

**Issue by fr500** [vurtun/zahnrad#55]
I have a menu item that is supposed to make a window focused (basically it's a window menu that will list all the open windows)

I am trying to achieve a sort of MDI interface and I want to use the Window menu to regain focus on windows that are on the background, so when I click Window->Demo Window
I'm doing zr_window_set_focus(ctx, "Demo Window"); but nothing really happens.

I also logged zr_window_has_focus on the Demo Window and it prints 1 so I don't really know what's going on.

![screenshot 2016-03-02 02 08 56](https://cloud.githubusercontent.com/assets/1721040/13453188/05ca18a2-e01c-11e5-88e6-197b93f56349.png)

**Comment by vurtun** [comment]
>> I also logged zr_window_has_focus on the Demo Window and it prints 1 so I don't really know what's going on.

Yeah that was my mistake. I only flagged the window as active but forgot to but the window on top of the window stack. Hopefully it is fixed now and behaves correctly.

**Comment by fr500** [comment]
Thanks, gonna test right away
