### ISSUE TITLE
Question: Open/Close windows dynamically

### ISSUE THREAD

**Issue by fr500** [vurtun/zahnrad#56]
On our project we will have several windows, settings, dialogs, etc.
Right now I have a sort of main function that controls everything:

```
static void zrmenu_frame(struct zrmenu *gui, int width, int height)
{
   struct zr_context *ctx = &gui->ctx;

   zrmenu_wnd_control(ctx, width, height, gui);   
   zrmenu_wnd_main(ctx, width, height, gui);
   zrmenu_wnd_demo(ctx, width, height, gui);
      
   zr_buffer_info(&gui->status, &gui->ctx.memory);
}
```

Actually opening a window later is not a problem, for instance I added a button to open wnd_control and then in my function I did this

```
static void zrmenu_frame(struct zrmenu *gui, int width, int height)
{
   struct zr_context *ctx = &gui->ctx;

   if (wnd_control)
      zrmenu_wnd_control(ctx, width, height, gui);   
   zrmenu_wnd_main(ctx, width, height, gui);
   zrmenu_wnd_demo(ctx, width, height, gui);
      
   zr_buffer_info(&gui->status, &gui->ctx.memory);
}
```

But after closing it and opening it several times the gui got somewhat stuck.
Now I'm just drawing the window offscreen which "works" but I would assume doing this would waste memory and CPU resources. 

Is there a correct way to handle this?

**Comment by fr500** [comment]
Now I realize I can set ZR_WINDOW_HIDDEN, is that the correct way to do this?

**Comment by vurtun** [comment]
> But after closing it and opening it several times the gui got somewhat stuck.

OK it should not get stuck this looks like a bug. I will take a look into what could cause that it is probably a list bug where a window or table is not correctly removed or added.

> Now I realize I can set ZR_WINDOW_HIDDEN, is that the correct way to do this?

`ZR_WINDOW_HIDDEN` is private flag and should not be used. But I just added a new function `zr_window_close` which does exactly that and is the prefered way of doing it.

**Comment by fr500** [comment]
Thanks
I'm still having some issues, for now I have this code:

This is my "main function" 
```
static void zrmenu_frame(struct zrmenu *gui, int width, int height)
{
   struct zr_context *ctx = &gui->ctx;

   zrmenu_wnd_main(ctx, width, height, gui);
   zrmenu_wnd_control(ctx, width, height, gui);
   zr_buffer_info(&gui->status, &gui->ctx.memory);
}
```
wnd_main contains the menu from which I can open and close other windows, etc.
The menu code on the main window reads as follows:

```
      if (zr_menu_text_begin(ctx, &menu, "Window", ZR_TEXT_LEFT|ZR_TEXT_MIDDLE, 120))
      {
          zr_layout_row_dynamic(ctx, 25, 1);

         if (zr_menu_item(ctx, ZR_TEXT_LEFT, "Control"))
         {
            if (!zr_window_is_closed(ctx, "Control"))
               zr_window_close(ctx, "Control");
         }
          zr_menu_end(ctx);
      }
```
But now when I click the related menu entry all the windows close and the Control window seems to just collapse, like this:

![collapse](https://cloud.githubusercontent.com/assets/1721040/13475566/b649e3a4-e091-11e5-823c-ad84bc3f135d.gif)
Am I doing something wrong?

**Comment by vurtun** [comment]
> But after closing it and opening it several times the gui got somewhat stuck.

This was a bug in the library and the new pushed commit hopefully fixing the closing and exposing bug (maybe have a look inside the new demo which uses a checkbox to hide and show windows). 

> But now when I click the related menu entry all the windows close and the Control window seems to just collapse, like this:

This is current limitation in the library. I do not support popups inside popups at the moment. So it is not possible at least at the moment to have menus with deeper menu levels (I am currently thinking about a solution will check it out and come back to that problem). 

Meanwhile I would recommend just changing the menu content on menu item click to achieve deeper menu levels. So you basically just have a variable for the current state of the menu and change the content to the currently active menu sub-tree.

**Comment by fr500** [comment]
fixed! works amazingly well
