### ISSUE TITLE
C89 violation

### ISSUE THREAD

**Issue by fr500** [vurtun/zahnrad#57]
RetroArch tries to use C89 whenever is possible too, like zahnrad itself.
When testing a C89 build we got the following error:

zahnrad.c:10772:30: error: ISO C forbids conversion of object pointer to function pointer type [-Werror=pedantic]

Might be something you want to look at since you're striving for C89 compatibility

**Comment by vurtun** [comment]
Yeah clang seems to completely ignore the warning or rather error which means that I have to switch to GCC. The problem should be fixed now.
